apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: hmoon
  labels:
    app.kubernetes.io/name: myapp
spec:
  serviceAccountName: hmoon-app-sa
  containers:
    - name: myapp
      image: hmoon630/sample-fastapi
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: my-secret
          mountPath: /etc/secret
          readOnly: true
        - name: db-secret
          mountPath: /etc/db-secret
          readOnly: true
  volumes:
    - name: my-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: my-secret
    - name: db-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: db-secret
