{{- range .Values.apps }}
{{- if .sampler.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-sampler
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .healthCheckPath }}
    alb.ingress.kubernetes.io/target-group-attributes: "deregistration_delay.timeout_seconds={{ .terminationGracePeriodSeconds }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ $.Values.sampler.servicePort }} # Service port number
      targetPort: {{ $.Values.sampler.port }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .healthCheckPath }}
    alb.ingress.kubernetes.io/target-group-attributes: "deregistration_delay.timeout_seconds={{ .terminationGracePeriodSeconds }}"
    {{- if .sampler.enabled }}
    weight: {{ sub 100 .sampler.weight | quote }}
    {{- else }}
    weight: "100"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .servicePort }} # Service port number
      targetPort: {{ .port }}
{{- end }}
