apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/<NODE_GROUP_ROLE_NAME>
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::<ACCOUNT_ID>:role/<ADMIN_ROLE_NAME>
      username: role:<ADMIN_ROLE_NAME>
      groups:
        - system:masters
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::<ACCOUNT_ID>:user/<USER_NAME>
      username: cluster-admin
kind: ConfigMap
