apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myapp-alb-requests
spec:
  scaleTargetRef:
    name: myapp
  minReplicaCount: 2
  maxReplicaCount: 10

  pollingInterval: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 15
  triggers:
    - type: aws-cloudwatch
      authenticationRef:
        name: keda-aws-credentials
      metadata:
        namespace: AWS/ApplicationELB
        dimensionName: LoadBalancer
        dimensionValue: app/myapp-alb/32c5cf1b343a3569
        metricName: RequestCount
        metricStat: Sum

        metricCollectionTime: "180" # Query for 3 minutes
        metricStatPeriod: "60" # Time unit is 60s
        metricEndTimeOffset: "30" # Skip for latest 30s

        targetMetricValue: "300"
        minMetricValue: "0"
        awsRegion: "us-east-1"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-credentials
spec:
  podIdentity:
    provider: aws
    identityOwner: keda
