apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-secret # k8s Secret .metadata.name
    creationPolicy: Owner
  data:
    - secretKey: dbusername
      remoteRef:
        key: <SECRET_NAME>
        property: username
    - secretKey: dbpassword
      remoteRef:
        key: <SECRET_NAME>
        property: password

    # # Retrieve tags from secret
    # - secretKey: tags
    #   remoteRef:
    #     key: <SECRET_NAME>
    #     metadataPolicy: Fetch
