apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: instanceid
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  target:
    name: instanceid # k8s Secret .metadata.name
    creationPolicy: Owner
  data:
    - secretKey: instanceid
      remoteRef:
        key: <PARAMETER_NAME>
