apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: myapp-security-group
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: myapp
  securityGroups:
    groupIds:
      - sg-04bfac281fc9246ec
      - sg-055394114cec188b0
