apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod # Pod 이름
spec:
  volumes:
    - name: html # volume 이름
      gitRepo:
        repository: https://github.com/luksa/kubia-website-example.git
        revision: master
        directory: .
      # git repo를 사용하기 위해서는 node에 git이 설치되어 있어야 합니다.
      # gitRepo는 파드가 종료되면 삭제되는 임시 저장소입니다.
  containers:
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html # mount할 volume이름을 지정합니다.
          mountPath: /usr/share/nginx/html # container의 mount 경로
          readOnly: true # 읽기 전용
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "100m"
