apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: hmoon
spec:
  volumes:
  - name: mongodb-data # Volume 이름
    persistentVolumeClaim: # PVC 연결
      claimName: mongodb-pvc # 연결할 PVC 이름
  containers:
  - image: mongo # 컨테이너 이미지
    name: mongodb # 컨테이너 이름
    volumeMounts: 
    - name: mongodb-data # 마운트할 Volume 이름
      mountPath: /data/db # 컨테이너의 Mount 경로
    ports:
    - containerPort: 27017
      protocol: TCP
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
