apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: SECRET_ARN
        objectType: secretsmanager
        objectAlias: my-secret
        jmesPath:
          - path: username
            objectAlias: dbusername
          - path: password
            objectAlias: dbpassword
  ## Sync with k8s Secret
  # secretObjects:
  #   - secretName: database # k8s Secret .matadata.name
  #     type: Opaque
  #     data:
  #       - key: username
  #         objectName: dbusername # Refers to <objectName> or <objectAlias>
  #       - key: password
  #         objectName: dbpassword
