apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: <SECRET_ID_OR_ARN>
        objectType: secretsmanager
        objectAlias: my-secret
        jmesPath:
          - path: username
            objectAlias: dbusername
          - path: password
            objectAlias: dbpassword
  # secretObjects:
  #   - secretName: database
  #     type: Opaque
  #     data:
  #       #- objectName: <objectName> or <objectAlias>
  #       - objectName: dbusername
  #         key: username
  #       - objectName: dbpassword
  #         key: password
